# Generated by Django 3.0 on 2021-09-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HstaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=10000000)),
                ('title', models.CharField(max_length=10000000)),
                ('FileName', models.CharField(max_length=10000000)),
                ('author', models.CharField(max_length=10000000)),
                ('chapter', models.CharField(max_length=10000000)),
                ('zip_file', models.FileField(upload_to='zip_input_file/')),
            ],
        ),
    ]
