# Generated by Django 3.2 on 2021-09-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hstadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hstadata',
            name='zip_file',
            field=models.FileField(upload_to=''),
        ),
    ]
