# Generated by Django 3.2 on 2021-09-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsta_app', '0002_auto_20210913_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hstadata',
            name='FileName',
        ),
    ]
