# Generated by Django 3.2 on 2021-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsta_app', '0003_remove_hstadata_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='hstadata',
            name='edition',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
