# Generated by Django 3.2 on 2021-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsta_app', '0004_hstadata_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedInputsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_names', models.CharField(max_length=10000000)),
                ('file_names', models.CharField(max_length=10000000)),
                ('output_status', models.CharField(max_length=10000000)),
            ],
        ),
    ]
