# Generated by Django 3.2 on 2021-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsta_app', '0005_uploadedinputsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedinputsinfo',
            name='date',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
