# Generated by Django 3.2 on 2021-10-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsta_app', '0006_uploadedinputsinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hstadata',
            name='email',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
